### ISSUE TITLE
Stage simulator

### ISSUE THREAD

**Issue by itayhubara** [windelbouwman/move-base-ompl#4]
Hi,

I tried running this code on stage simulator enviroment. I acctually have no problem running it but  I cant make the robot follow the plan. I noticed  that RRTConnect or any other planner, finds a path but when it tried to send the path as a plan (geometry_msgs) it recives the wrong x,y values. I think the problem is in the get_xy_theta_v function

Can you please help?

Best,
Itay

**Comment by windelbouwman** [comment]
Hey Itay!

Cool you checked out my code! I have not run it for a long time, and
eventually abandoned it in favor of move-base its own planner. Perhaps
it has to be ported to the new ros version. You can fork the project and
try to do it, probably a good test set is also needed or a simulation
test-case?

In short: I will probably not be able to help you. What do you wish to
achieve?

Best regards,
Windel

**Comment by itayhubara** [comment]
I mange to use OMPL library for that. 
Anyway thanks..

Best,
Itay
